_wandb:
    value:
        cli_version: 0.22.2
        e:
            qyzoafiqrlthv714th3gcjvveytxi5l6:
                colab: https://colab.research.google.com/notebook#fileId=13YydpxOCTCWk7Rsae16DJoKeDnOpIe5X
                cpu_count: 1
                cpu_count_logical: 2
                disk:
                    /:
                        total: "115658190848"
                        used: "42596954112"
                email: 142502019@smail.iitpkd.ac.in
                executable: /usr/bin/python3
                host: 498f6ab90d11
                memory:
                    total: "13605851136"
                os: Linux-6.6.105+-x86_64-with-glibc2.35
                program: Untitled1.ipynb
                python: CPython 3.12.12
                root: /content
                startedAt: "2025-10-28T04:44:09.066300Z"
                writerId: qyzoafiqrlthv714th3gcjvveytxi5l6
        m: []
        python_version: 3.12.12
        t:
            "1":
                - 5
                - 53
                - 105
            "2":
                - 5
                - 53
                - 105
            "3":
                - 2
                - 13
            "4": 3.12.12
            "5": 0.22.2
            "8":
                - 1
                - 12
            "10":
                - 20
            "12": 0.22.2
            "13": linux-x86_64
n_estimators:
    value: 50
random_state:
    value: 42
